version: "3.8"
services:
  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=local_dev_user
      - POSTGRES_PASSWORD=bsKD7eNNGqdJ5X52LWDcCiLv6
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
